# Generated by Django 3.0.4 on 2020-10-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_id', models.CharField(auto_created=True, default='0', max_length=100)),
                ('user_id', models.CharField(default='0', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AchievesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='makehabitsapp.HabitModel')),
            ],
        ),
    ]
