# Generated by Django 3.0.4 on 2020-10-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makehabitsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitmodel',
            name='habit_id',
        ),
    ]
