# Generated by Django 3.0.4 on 2020-09-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makehabitsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitmodel',
            old_name='title',
            new_name='tittle',
        ),
    ]
