# Generated by Django 3.0.4 on 2020-09-07 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makehabitsapp', '0002_auto_20200906_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitmodel',
            old_name='tittle',
            new_name='title',
        ),
    ]
