# Generated by Django 3.0.4 on 2020-09-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makehabitsapp', '0003_auto_20200907_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmodel',
            name='user_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
