# Generated by Django 3.0.4 on 2020-09-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makehabitsapp', '0006_auto_20200928_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('habit_id', models.CharField(max_length=100)),
                ('habit_nm', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='achieves',
            field=models.ManyToManyField(related_name='habit_2_achieves', to='makehabitsapp.AchievesModel'),
        ),
    ]
